FROM python:3.12-slim

WORKDIR /app

# Nödvändigt för att psycopg2 ska kunna kompileras mot Postgres
RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]